spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pim
    username: usr
    password: admin
  flyway:
    enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE